// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lawyer.api.leads.datastore.mssql.DatabaseContext;

#nullable disable

namespace lawyer.api.leads.datastore.mssql.Migrations
{
    [DbContext(typeof(LawyersContext))]
    [Migration("20250903194511_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lawyer.api.leads.datastore.mssql.Model.ExampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("PropertyOne")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyTwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Examples", "leads");
                });

            modelBuilder.Entity("lawyer.api.leads.datastore.mssql.Model.LeadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brief")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdLawFirm")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdLeadState")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdLeadState");

                    b.ToTable("Leads", "leads");
                });

            modelBuilder.Entity("lawyer.api.leads.datastore.mssql.Model.LeadMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdLead")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdLead");

                    b.ToTable("LeadMessages", "leads");
                });

            modelBuilder.Entity("lawyer.api.leads.datastore.mssql.Model.LeadStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeadStates", "leads");
                });

            modelBuilder.Entity("lawyer.api.leads.datastore.mssql.Model.LeadEntity", b =>
                {
                    b.HasOne("lawyer.api.leads.datastore.mssql.Model.LeadStateEntity", "LeadState")
                        .WithMany("Leads")
                        .HasForeignKey("IdLeadState")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeadState");
                });

            modelBuilder.Entity("lawyer.api.leads.datastore.mssql.Model.LeadMessageEntity", b =>
                {
                    b.HasOne("lawyer.api.leads.datastore.mssql.Model.LeadEntity", "Lead")
                        .WithMany("LeadMessages")
                        .HasForeignKey("IdLead")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("lawyer.api.leads.datastore.mssql.Model.LeadEntity", b =>
                {
                    b.Navigation("LeadMessages");
                });

            modelBuilder.Entity("lawyer.api.leads.datastore.mssql.Model.LeadStateEntity", b =>
                {
                    b.Navigation("Leads");
                });
#pragma warning restore 612, 618
        }
    }
}
